### ISSUE TITLE
Genserver replication across nodes in the cluster ?

### ISSUE THREAD

**Issue by jaybe78** [silbermm/ecs_example#1]
@silbermm 
Hello and Thanks for the great work.

I would like to know if genserver would be replicated across all nodes with that architecture or is still required to use something like horde ?

**Comment by silbermm** [comment]
Hey @jaybe78 

In this architecture, each node runs the GenServer, so there is no need for a tool like hoarde

**Comment by silbermm** [comment]
Hi @jaybe78 ,

This architecture doesn't prescribe any strategies for replicating GenServers. You could use a tool like hoarde or swarm for distributed registries and supervisors.

**Comment by jaybe78** [comment]
> Hi @jaybe78 ,
> 
> This architecture doesn't prescribe any strategies for replicating GenServers. You could use a tool like hoarde or swarm for distributed registries and supervisors.

Yes That's what I thought !
Horde looks really powerful, by any chance have you used either of those in production ? 
Its that stable ?

Thx

**Comment by silbermm** [comment]
I have used Swarm before and really liked it. While I haven’t used Hoard, I have heard good things about it.
